### ISSUE TITLE
Collaboration schedule

### ISSUE THREAD

**Issue by mhassany** [mhassany/sit-690#1]
Identify how and when we will interact and work together is very important, so let's decide how to do that. We can either:

- Meet in person in a specific datetime
- Meet online in a specific datetime
- or ...

Please vote by responding to this issue.
And provide your preferred your datetime or more detail.

Thanks

**Comment by SachinMCReddy** [comment]
Meet in person in a specific daytime

**Comment by mhassany** [comment]
> Meet in person in a specific daytime

@SachinMCReddy Can you also mention your preferred datetime?

Thanks

**Comment by SachinMCReddy** [comment]
Wednesday Morning

**Comment by Svaity** [comment]
I have my internship on Monday Thursday(half day) and Friday so evening on those days online meeting is fine 
Tuesday and Thursday I'll be on campus do would be okay meeting in person

**Comment by BenjiTheC** [comment]
**Vote**: Meet in person in a specific daytime.
**Available schedule**: anytime in Tuesday afternoon (1-4pm), Wednesday morning (9am-12pm) and Friday afternoon (1-3pm)

**Comment by tanmaybhoir09** [comment]
Meet in person in a specific daytime
Available Schedule: Monday-Wednesday anytime, Thursday morning,

**Comment by mhassany** [comment]
Note that this meeting is mostly (or only) for reviewing our progress, although we can organize a meeting separately with each other in case of working on same issue in person.

Because of everyone timing issue, I suggest we have the meeting **every Tuesday after our class**. 

FYI: Here is the summary of our schedule:
<img width="426" alt="Screen Shot 2019-09-08 at 7 12 09 PM" src="https://user-images.githubusercontent.com/44843729/64495798-93d4ab80-d26c-11e9-9bf0-14902380cd4c.png">


@SachinMCReddy @Svaity @BenjiTheC @tanmaybhoir09
