### ISSUE TITLE
Feature: User Registration

### ISSUE THREAD

**Issue by tanmaybhoir09** [mhassany/sit-690#11]
User can register to the website using their Gmail or Facebook accounts, doing so they will be able to view their order status and history.

**Comment by mhassany** [comment]
The backend API is available under following urls:
- /api/v1/login, to login
- /api/v1/logout, to logout
- /api/v1/register, to register
- /api/v1/password/email, to send password reset link to the user email
- /api/v1/password/reset, to reset the password
- /api/v1/email/verify/{id}/{hash}, to verify the user email address
- /api/v1/email/resend, to resend the verification email address

Check the "/api/documentation" for more information.

**Comment by mhassany** [comment]
implemented in angular
