### ISSUE TITLE
Feature: Retrieving order via reference number

### ISSUE THREAD

**Issue by tanmaybhoir09** [mhassany/sit-690#12]
The user would be provided with an order reference number which they can use to retrieve information about that specific order, or load and view that order on the website.

**Comment by mhassany** [comment]
@BenjiTheC backend for this feature is implemented and can be accessed via `/orders` API.
please check the openapi doc for more information. 
let me know if you have any question.
thanks

**Comment by mhassany** [comment]
implemented in angular
