### ISSUE TITLE
Reference: How to call APIs

### ISSUE THREAD

**Issue by BenjiTheC** [mhassany/sit-690#13]
# Determine the API calls data structure

I will start building the frontend by constructing the API calls and what data is frontend receiving from backend with what structure. I think we will need to hold a in person meeting to discuss this.

## What needs to be discussed

1. How to construct the routes.
2. For each request type (`GET`, `POST`, `PUT`, `DETELE`, etc), what data, **in the format of JSON**, is expected to be received by the frontend.

## For DB people

It's good to think about how to store the data in the Database here as well. Specifically:

1. How many table are we building?
2. For each table in the database, what object is represented?
3. Based on the data format frontend requires, what DB operation should be constructed.

**Comment by mhassany** [comment]
I don't have any suggestion for the structure of our requests, right now. but i think we can start with a simple one, and improve it overtime. 

for the number of tables, and database. i also suggest the same: starting from somewhere (the most essential component), and moving upward. in each step we can identify details, design and implement our database, requests, and urls accordingly.

i suggest to keep this topic open so we share our findings regarding them here.

**Comment by mhassany** [comment]
Hi everyone, 
Most of our APIs will have following syntax:
```
API URL Format:
 GET    /object         <-- list the object
 POST   /object         <-- create new object
 GET    /object/{id}    <-- view the specific object
 PUT    /object/{id}    <-- update the specific object
 DELETE /object/{id}    <-- delete the specific object
```

**Comment by BenjiTheC** [comment]
> Hi everyone,
> Most of our APIs will have following syntax:
> 
> ```
> API URL Format:
>  GET    /object         <-- list the object
>  POST   /object         <-- create new object
>  GET    /object/{id}    <-- view the specific object
>  PUT    /object/{id}    <-- update the specific object
>  DELETE /object/{id}    <-- delete the specific object
> ```

This syntax is confusing and vague, I was struggling to figure out what's the returned object's structure for each api call. And I couldn't find any info helpful from the existing documentation.

I make a `GET http://localhost:8000/api/v1/restaurant/type` and it gives me a `404` response. Is it possible to just update the simple structure of returned type for each route somewhere?

**Comment by mhassany** [comment]
try:
.../api/v1/restaurant/types

**Comment by BenjiTheC** [comment]
> ## try:
> .../api/v1/restaurant/types
> you can visit
> .../api/documentation
> to explore the available APIs.

I didn't find a repo path with /api/documentation, so I will assume that this is a url that is callable by frontend. I will take a look after 12PM.

**Comment by mhassany** [comment]
do you have the recent version of code on your local machine?

**Comment by BenjiTheC** [comment]
Yes, I stashed my change and pull down the latest code this morning. I will get back to you later after I look into it
