### ISSUE TITLE
Reference: Color theme

### ISSUE THREAD

**Issue by BenjiTheC** [mhassany/sit-690#14]
# Determine the UI color theme

One important about collaboration of UI and frontend dev is to set up a set of colors that is going to be used for UI design and Frontend development. Let's make the rule for what color to use and how to describe each color

## What needs to be discussed

A set of colors in the format of `colorName : hexColorCode` map in JSON format, e.g.

```JSON
{
    "azure": "007FFF",
    "black": "000000"
}
```

## How many colors do we need

I think we need three set of colors:

1. **Primary color**: The color we used for major signal/brand/logo etc, that represent the product. Expected no more than 5.
2. **Secondary color**: Assistant color that help adding some accent for the feature. Expected no more than 6.
3. **Text color**: Categorize the text based on functionality - link, content, info, header, etc.

**Comment by Svaity** [comment]
this is my fav tool to decide color scheme for web
http://colormind.io/bootstrap/

Click on generate(or select manually) and scroll down to see how the website looks with that color scheme
I feel that the food menu and options would work well with the card styled design
like this
![Screen Shot 2019-09-17 at 5 47 16 PM](https://user-images.githubusercontent.com/43662680/65082256-780b8c80-d973-11e9-9c16-cefe0df1595b.png)

I though about using these 2 color palettes
Primary:(Some shade of blue) 6396AD or #01579b
Secondary color: (Complimenting shade of blue(light or dark) or contradicting shade like Maroon red)
FontColor: White / Black based on the background color
![Screen Shot 2019-09-17 at 6 03 50 PM](https://user-images.githubusercontent.com/43662680/65083109-a5593a00-d975-11e9-8629-b4f413c434dc.png)
Or this 
![Screen Shot 2019-09-17 at 5 22 32 PM](https://user-images.githubusercontent.com/43662680/65083110-a722fd80-d975-11e9-84b7-f503ae393fd1.png)

**Comment by BenjiTheC** [comment]
We will probably need more than one primary color and more than one secondary color. And I would suggest using some color that's not `#000000` (not absolute black) for font color - a very very dark blue would be better? That's what Amazon used.

**Comment by Svaity** [comment]
Primary Color 
#004362

**Comment by mhassany** [comment]
closing this issue because we move back to angular (we are using Azure as the color)
