### ISSUE TITLE
Feature: complete restaurant profile

### ISSUE THREAD

**Issue by mhassany** [mhassany/sit-690#19]
restaurant owner/staff should complete the restaurant profile and successful registration

**Comment by mhassany** [comment]
@vaityshrey @SachinMCReddy when can you finish the requirements for this feature?

**Comment by SachinMCReddy** [comment]
The requirements for restaurant profile and adding menu completed.

**Comment by mhassany** [comment]
@SachinMCReddy i don't see the requirement details for restaurant profile in the requirement list file. Can you please confirm. Thanks

**Comment by BenjiTheC** [comment]
Let discuss the structure for `req.body` for the `POST` request of restaurant registration.

**Comment by mhassany** [comment]
Below is the list of attributes for each object type in the system.
Check the api-filestore.php, api-restaurant.php for the API urls.
```
// restaurant_types
{
    // "id" => "auto_generated"
    "name" => "required|min:3|max:64|unique:restaurant_types",
    "description" => "max:128"
}

// file_objects
{
    // "uid" => "auto_generated"
    "file" => "a file"
}

// restaurant_registration_requests
{
    // "id" => "auto_generated"
    "name": "required|min:3|max:128",
    "phone": "required|min:3|max:32",
    "email": "required|email|max:128",
    "address": "required|min:3|max:256",
    "type_id": "restaurant_types.id",
    "logo_uid": "required|filestore_object",
    "legal_info": "required|min:3|max:256",
}


```

**Comment by BenjiTheC** [comment]
The `legal_info` part is kind of confusing me. Is it supposed to be a text area or legal material submitted as file?

**Comment by tanmaybhoir09** [comment]
@BenjiTheC the legal_info is supposed to be a file upload

**Comment by mhassany** [comment]
I found out this feature is not necessary. 
So I am going to close this one.
