### ISSUE TITLE
Feature: register restaurant

### ISSUE THREAD

**Issue by mhassany** [mhassany/sit-690#2]
A restaurant owner can creates a restaurant profile to register her business on the website.

**Comment by mhassany** [comment]
What information is needed for registering a restaurant?

@tanmaybhoir09 please work on this.
Thanks

**Comment by mhassany** [comment]
@SachinMCReddy please work with Tanmay on this.

Please try to finish it by the end of this Wed - Sep 18, 2019.
Because we have to work on the user interface and backend.

Thanks

**Comment by mhassany** [comment]
@vaityshrey please follow up on this, cause we need the ui sketches at the end of next day.

**Comment by mhassany** [comment]
@tanmaybhoir09 @SachinMCReddy please update us. thanks

**Comment by tanmaybhoir09** [comment]
[Restaurant Registration Requirements.docx](https://github.com/mhassany/sit-690/files/3638088/Restaurant.Registration.Requirements.docx)

**Comment by mhassany** [comment]
@tanmaybhoir09 put it in the "requirements list" google doc.

**Comment by tanmaybhoir09** [comment]
got it @mhassany

**Comment by mhassany** [comment]
@BenjiTheC 
I finished the backend for registering a restaurant. 
Please check the repo/backend/routes/api-**.php files for the all API urls.
To understand the required/response payload for each API please follow the url in the associated controller.

Let me know if you have any question.
Thanks

**Comment by mhassany** [comment]
@vaityshrey when can you finish the wireframe for this feature?

**Comment by mhassany** [comment]
@BenjiTheC how long does it take you to deliver the ui for this feature?

**Comment by Svaity** [comment]
![Screen Shot 2019-09-27 at 10 57 05 PM](https://user-images.githubusercontent.com/43662680/65810588-271d4480-e17a-11e9-8154-037a8c84feda.png)

**Comment by mhassany** [comment]
@vaityshrey we don't have the option "does the restaurant deliver" in registration form.
@BenjiTheC please use this prototype for the restaurant registration. (but ignore the input elements that are not in our registration form - backend)

**Comment by mhassany** [comment]
@BenjiTheC close this issue if the functionality is implemented. thanks

**Comment by mhassany** [comment]
@BenjiTheC close this issue if the functionality is implemented. thanks

**Comment by mhassany** [comment]
implemented in angular
