### ISSUE TITLE
Prototypes

### ISSUE THREAD

**Issue by mhassany** [mhassany/sit-690#22]
Although we don't have the detail for each step/feature of our system, let's create a generic prototype that shows the flow of user interaction from page to page. We can include the details that we have, or wants to have. 

This prototypes doesn't necessarily reflect the final system, but it is a demo of what we want to have (which definitely may change over time).

-- lets use wireframe for working on our prototypes.

@Svaity

**Comment by BenjiTheC** [comment]
Great, I need this desprately.
