### ISSUE TITLE
Feature: Adding menu to the website

### ISSUE THREAD

**Issue by tanmaybhoir09** [mhassany/sit-690#3]
The restaurant operator staff can add/remove dishes from menu to manage their restaurant menu on the website.

**Comment by mhassany** [comment]
What information is needed for adding menu for a restaurant?
What kind of dishes are usually in a menu? What is different between them?

@tanmaybhoir09 Please find enough details about this. 
@SachinMCReddy please work with Tanmay on this.

**Comment by mhassany** [comment]
Please try to finish it by the end of this Thu - Sep 19, 2019.
Because we have to work on the user interface and backend.

Thanks

**Comment by mhassany** [comment]
@vaityshrey please follow up on this, cause we need the ui sketches at the end of next day.

**Comment by SachinMCReddy** [comment]
@mhassany Sure, Will follow up with tanmay on that.

**Comment by mhassany** [comment]
@tanmaybhoir09 @SachinMCReddy please update us. thanks

**Comment by mhassany** [comment]
@vaityshrey @SachinMCReddy when can you finish the requirements for this feature?

**Comment by SachinMCReddy** [comment]
Adding menu requirements completed

**Comment by mhassany** [comment]
@SachinMCReddy i don't see the requirement details for adding menu in the requirement list file. Can you please confirm. Thanks

**Comment by Svaity** [comment]
![Screen Shot 2019-09-28 at 6 39 18 PM](https://user-images.githubusercontent.com/43662680/65823179-6baeeb80-e21f-11e9-9aa6-c1acc0678ade.png)

**Comment by Svaity** [comment]
![Group 3](https://user-images.githubusercontent.com/43662680/65823202-e0822580-e21f-11e9-9e24-b886f6412643.png)

**Comment by mhassany** [comment]
I have finished the backend logic for managing menu.
please check the http://local-eats.nili.af/api/documentation to check the apis.

**Comment by mhassany** [comment]
@BenjiTheC  close this issue if the functionality is implemented. thanks

**Comment by mhassany** [comment]
The backend API is available under following urls:
- /restaurants/menu/categories
- /restaurants/menu/dishes
Check the "/api/documentation" for more information.

@BenjiTheC close this issue if the functionality is implemented. thanks

**Comment by mhassany** [comment]
implemented in angular
