### ISSUE TITLE
Feature: Restaurant receives food orders

### ISSUE THREAD

**Issue by tanmaybhoir09** [mhassany/sit-690#4]
The restaurant operator staff are able to see incoming orders on the dashboard and would be able to process them according to the requests.

**Comment by mhassany** [comment]
@BenjiTheC backend for this feature is implemented and can be accessed via `/orders` API.
please check the openapi doc for more information. 
let me know if you have any question.
thanks

**Comment by mhassany** [comment]
@BenjiTheC  close this issue if the functionality is implemented. thanks

**Comment by mhassany** [comment]
implemented in angular

**Comment by mhassany** [comment]
implemented in angular
