### ISSUE TITLE
Is there a field storing result of a restaurant registration requests?

### ISSUE THREAD

**Issue by BenjiTheC** [mhassany/sit-690#55]
Looking at the open API I couldn't find the result - approved/rejected/canceled shown in any fields of data retrieve from `/restaurant/registration-requests`. Do we have a place store it? Or a restaurant registration is just simply moved to the restaurants?

If we have the field, can we add it/how should I retrieve it from the backend?

**Comment by mhassany** [comment]
fixed in this [commit](https://github.com/mhassany/sit-690/commit/fbfb558a4fb2794e831b66f7032570cf735b1723)

**Comment by BenjiTheC** [comment]
Great, thank a lot!
