### ISSUE TITLE
Couldn't find any API for fetching categories of dish from backend

### ISSUE THREAD

**Issue by BenjiTheC** [mhassany/sit-690#56]
I can't find the api mentioned in title, the only api I found is the `/restaurants/menu/categories`. Which returns categories by restaurant, not for dishes. Are these two identical?

**Comment by mhassany** [comment]
thanks for mentioning it.

`/restaurants/menu/categories` provide CRUD operation for the menu categories for each restaurant (so each restaurant can have different categories).

you can use this `/restaurants/menu/categories/defaults` url to get the default categories and use it as a suggestion (when user try to create their menu categories for their restaurant). I added this in the latest commit which is merged with the "current-sprint".
https://github.com/mhassany/sit-690/pull/58
