### ISSUE TITLE
Does backend POST request accept JSON data?

### ISSUE THREAD

**Issue by BenjiTheC** [mhassany/sit-690#60]
Just wondering if the `POST` request to backend receive JSON data or not. For example, for restaurant registration, I can serialize the form data into JSON format before I send it to backend - simply curious and it's fine if only form data is accepted but it would be nice to have.

**Comment by mhassany** [comment]
Yes, both the request bod and response body is in JSON format except the filestore api that is used to upload and download the files.

**Comment by mhassany** [comment]
close this issue if your question is answered. thanks
