### ISSUE TITLE
Minimal mandatory data for add dish???

### ISSUE THREAD

**Issue by BenjiTheC** [mhassany/sit-690#64]
What is the minimal add dish mandatory data? The documentation shows that it requires only `{ category_id, name, price }` for a successful post request to the `POST /restaurants/menu/dishes` but I'm getting a 500 status code.

**Comment by mhassany** [comment]
can you provide the detail of 500 error.

**Comment by BenjiTheC** [comment]
case solved last night working with Mohammad, closing the issue
